language: python

python:
  - "3.6"
  - "3.7-dev"

cache:
    pip: true

install:
    - pip install -U -r requirements/test.txt
    - pip install coveralls
    - pip install -e .

# command to run tests
script: make coverage

after_success:
  - coveralls


