version: "3"

services:

    postgresql:
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        image: postgresql-mishmash-devel
        container_name: PostgreSQL-MishMash-devel
        environment:
            POSTGRES_PASSWORD: g4b4g3
            DB_NAME: MishMash_devel
            DB_USER: mishmash
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5


    mishmash: &mishmash-image
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VERSION: $VERSION
        image: mishmash:latest


    mishmash-publish:
        <<: *mishmash-image
        image: nicfit/mishmash:$VERSION

