version: "3"

services:

    postgres:
        image: postgres:10-alpine
        container_name: PostgreSQL-mishmash-devel
        environment:
            POSTGRES_DB: MishMash-devel
            POSTGRES_USER: mishmash
            POSTGRES_PASSWORD: g4b4g3
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5


    mishmash: &mishmash-image
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VERSION: $VERSION
        image: mishmash


    mishmash-publish:
        <<: *mishmash-image
        image: nicfit/mishmash:$VERSION

